### ISSUE TITLE
No timeout for inactive peers?

### ISSUE THREAD

**Issue by kenaniah** [l7mp/stunner#107]
We have a situation in which some of the peers do not signal their disconnection (and STUNner does not appear to be handling UDP timeouts). Downstream, our application is unable to detect these disconnections (since its connection to STUNner is still live). 

Is there a way to detect and/or configure peer disconnections & timeouts?

**Comment by rg0now** [comment]
STUNner is in fact a glorified proxy, so timeouts may refer to connections to clients or peers. The client-side connection is always TURN so [RFC8856](https://datatracker.ietf.org/doc/html/rfc8656) applies: allocations last for [10 minutes](https://datatracker.ietf.org/doc/html/rfc8656#section-6) by default without being refreshed, but clients can [request a custom allocation lifetime in Allocate or Refresh requests](https://datatracker.ietf.org/doc/html/rfc8656#name-lifetime). If you want your TURN clients to time out fast request a small lifetime, STUNner will respect such requests (provided your TURN client lib supports setting custom timeouts, I guess most JavaScript WebRTC stacks won't). The peer-side connection is always plain UDP and STUNner uses the default idle UDP timeout of the platform, which can be anything from 30 seconds to several minutes.

**Comment by kenaniah** [comment]
Perfect. Thanks for the info and the links!
