### ISSUE TITLE
turn ERROR: Failed to handle datagram: failed to create stun message from packet: unexpected EOF: not enough bytes to read header

### ISSUE THREAD

**Issue by gtokarz** [l7mp/stunner#122]
When using UDP-CONNECT health monitor stunner-daemon spams following logs:
turn ERROR: Failed to handle datagram: failed to create stun message from packet: unexpected EOF: not enough bytes to read header

Setup:
Service as NodePort + manual openstack octavia loadbalancer with UDP-CONNECT health monitor. All seems working just the logs are cluttered a bit with error message.

**Comment by rg0now** [comment]
Closing this for now. If this comes up again, we will need to address this in upstream pion/turn. Please, reopen if you still think we should fix this.
