### ISSUE TITLE
srflx ICE candidate wrong ip?

### ISSUE THREAD

**Issue by gtokarz** [l7mp/stunner#129]
Hello I am trying to test ICE tricking from my configuration, it is running behind loadbalancer as follows:
LB <=> k8s with 3 nodes
When testing ICE gathering here https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/
It responds with **srflx** candidate equal to one of  node ips instead of client ip, when testing with some public stun servers it seems returns **srflx** candidate with correct ip address (client ip not the node ip). Is it expected or a bug?

**Comment by rg0now** [comment]
This is expected. Using STUNner as a STUN server (this is the thing that generates the **srflx** candidates) is strongly discouraged: this only works if you deploy STUNner in the host-network namespace and you may need to run without a load balancer. The recommended operational mode is to use STUNner as a TURN server to generate **relay** ICE candidates: this works even if you deploy STUNner over a regular private pod IP. We even recommend disabling STUN candidate collection all together by enforcing the `iceTransportPolicy=relay` setting in your ICE server configuration. See more on ICE models for STUNner [here](https://github.com/l7mp/stunner/blob/main/docs/DEPLOYMENT.md#ice-models).

**Comment by ben-z** [comment]
> This is expected. Using STUNner as a STUN server (this is the thing that generates the **srflx** candidates) is strongly discouraged

Can this be documented in the main README? Based on the project's name STUNner and the README, I assumed that this project would work like any public STUN+TURN server. But only after a long setup and debug session to see why all of the connections are relayed that I came across this issue.

**Comment by rg0now** [comment]
This is done now, see https://github.com/l7mp/stunner/blob/main/README.md#features.

Actually, we owe you an ack for pushing for STUN. You (and a couple of other users on Discord) were a great motivation to go after the STUN use case.
