### ISSUE TITLE
SRS integration?

### ISSUE THREAD

**Issue by slps970093** [l7mp/stunner#131]
Is it possible to use SRS integration to solve WebRTC scaling issues in AutoScaling

https://ossrs.net/lts/zh-cn/

**Comment by levaitamas** [comment]
Hi @slps970093,
We have not considered integrating STUNner with SRS yet. If I understood SRS correctly, they are focusing on livestreaming and has a nice selection of supported protocols. The WebRTC integration seems [kinda limited](https://ossrs.net/lts/en-us/docs/v6/doc/webrtc#webrtc-over-tcp) for me and might lack TURN support?! Anyway if you somehow manage to configure TURN servers for SRS, STUNner can definitely there to help you to scale your workloads in k8s.

**Comment by slps970093** [comment]
Hi~ @levaitamas 
Because my purpose is to expand the webrtc server. According to my understanding, there will be problems with load balancing when k8s pod replicas are 2 or more. Assume that my srs webrtc port is 8000 but the internal IP of each pod is different. I don’t know. Can this repo help me expand?

**Comment by levaitamas** [comment]
Absolutely, scaling media workloads is one of the killer features of STUNner. Let me refer you to the docs to read more about the architecture: https://docs.l7mp.io/en/stable/DEPLOYMENT/#media-plane-deployment-model

**Comment by rg0now** [comment]
Also, the STUNner [scaling guide](https://github.com/l7mp/stunner/blob/main/docs/SCALING.md) might be of interest here.

**Comment by rg0now** [comment]
This issue has been stale for a couple of months, closing it for now. Feel free to reopen if anything new comes up.
