### ISSUE TITLE
stunner.l7mp.io/service-type: ClusterIP doesn't work

### ISSUE THREAD

**Issue by caffeinism** [l7mp/stunner#150]
### Description

If I specify `stunner.l7mp.io/service-type: ClusterIP`, service object will not be deployed.

### Steps to Reproduce

Specify `stunner.l7mp.io/service-type: ClusterIP` in the Gateway's annotation.

**Expected behavior:** The service must be deployed with ClusterIP.

**Actual behavior:** The service is not created.

### Versions

0.19.0

#### Operator logs 

```
...
Service \"gateway-udp\" is invalid: spec.externalTrafficPolicy: Invalid value: \"Cluster\": may only be set for externally-accessible services"
```

**Comment by rg0now** [comment]
Thanks for the report. Seems like two recent new features interfering in unexpected ways. We'll look into this ASAP.

**Comment by rg0now** [comment]
This is now fixed in https://github.com/l7mp/stunner-gateway-operator/commit/c73baa4f8064a4836e192452770a58de08b949cf. Thanks for the report.
