### ISSUE TITLE
OCI Network Loadbalancer only supports sessionAffinity: None for v0.20.0

### ISSUE THREAD

**Issue by atomic-tang** [l7mp/stunner#155]
### Description

Upgraded to version 0.20.0 with helm on OCI but the network loadbalancer failed to start up due to the following error:
```
Error syncing load balancer: failed to ensure load balancer: invalid service: OCI only supports SessionAffinity "None" currently
```

Other loadbalancers on OCI cannot be used as they do not support UDP traffic.

**Comment by rg0now** [comment]
Guess we'll have to add [yet another Gateway annotation](https://github.com/l7mp/stunner/blob/main/docs/GATEWAY.md#load-balancer-configuration) to optionally disable client affinity. That being said, the policy of OKE to straight our reject an LB Service using a feature that's been GA for I don't know how many Kubernetes releases is at least questionable I'd say.

**Comment by rg0now** [comment]
Could you please make a quick test to check whether the fix solved your problem? Just add the annotation `stunner.l7mp.io/disable-session-affinity: true` to your Gateway, this would revert the LB Service session affinity setting to None. Hopefully this will make OCI happy. 

Feel free to reopen if something new shows up.
