### ISSUE TITLE
[Question] Co-existence with Cilium?

### ISSUE THREAD

**Issue by jackmaninov** [l7mp/stunner#160]
Hello. In #8 it is mentioned that in 2022 STUNner could not interoperate with Cilium. I'm wondering has there has been any updates in that regard? 

I am evaluating whether I can deploy STUNner alongside a cluster using Cilium as CNI. Thank you.

**Comment by levaitamas** [comment]
Hi @jackmaninov,

There should be no issue with using STUNner with Cilium. I guess we run on Cilium in Google Cloud. 
In #8, we discussed our upcoming eBPF offload that might interfere with Cilium. 

I hope this answers your question. I am closing this for now, but feel free to reopen if you encounter any issues related to Cilium+STUNner or open new ones if you have any other questions or issues. I also invite you to our [Discord server](https://discord.gg/DyPgEsbwzc). Last but not least, if you need any extra services, we are in the consultancy business as [l7mp.io](https://l7mp.io/#/services).

**Comment by jackmaninov** [comment]
One small conflict I would note is that the `stunner-gateway-operator` helm chart installs v1.0.0 of the gateway-api CRDs, but recent versions of cilium require v1.1.0+. 

Other projects I've seen that use gateway-api tend to not bundle the CRDs, and they're iterating so rapidly anyways. It would be worth making this installation optional in your chart.

**Comment by levaitamas** [comment]
Hi @jackmaninov,
You can use your own gateway-api CRD with STUNner. See the docs: https://docs.l7mp.io/en/stable/INSTALL/#skip-install-crds
