### ISSUE TITLE
RTD: Fix alert blockquotes

### ISSUE THREAD

**Issue by davidkornel** [l7mp/stunner#169]
### Description

Alert blockquotes are not rendered by read the docs. We should fix them somehow so the [docs](https://docs.l7mp.io/en/stable/) won't look like this:
![image](https://github.com/user-attachments/assets/819e988e-35bb-4077-954a-6414e9496033)

**Comment by davidkornel** [comment]
@levaitamas i think you mentioned this issue somewhere, but could not find it. Do you have any idea how we could/should fix this?

**Comment by rg0now** [comment]
I recommend we remove the special blockquote syntax. It's not portable and even GitHub routinely breaks rendering. Just use running text line "Note that..." etc.

**Comment by levaitamas** [comment]
Should be fixed in `latest`. @davidkornel, can you please double check here: https://docs.l7mp.io/en/latest/?

**Comment by levaitamas** [comment]
Fixing the current stable seemed too much hustle. In case the latest looks good, the next stable (i.e., v1.0.0) will be rendered correctly too.

**Comment by levaitamas** [comment]
Just for the record, this was the fix: https://github.com/l7mp/stunner/commit/5596d84d81d286ab9e36b2f341525df25234a43d

**Comment by davidkornel** [comment]
Missed it, thanks. Closing this.
