### ISSUE TITLE
Issue in installation document

### ISSUE THREAD

**Issue by mahdidarabi** [l7mp/stunner#176]
### Description

The url of installation of CRDs for K8s gateway-api is invalid

### Steps to Reproduce

Run below command from document:
`kubectl apply -k github.com/kubernetes-sigs/gateway-api/config/crd?ref=v1.0.0`

**Expected behavior:** Installation of gateway-api CRDs to be complete.

**Actual behavior:** Throws error with this msg: `no matches found: github.com/kubernetes-sigs/gateway-api/config/crd?ref=v1.0.0`

### Versions

1.0.0

**Comment by levaitamas** [comment]
Hi @mahdidarabi !

Thanks for letting us know. @davidkornel could this (v1.0.0, standtard-install) be a valid alternative: https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.0.0/standard-install.yaml ?

**Comment by davidkornel** [comment]
Reopening: Although it has been fixed and close I am still curious

Hi @mahdidarabi and @levaitamas. 

This seems confusing, as it works for me:
```
kubectl apply -k github.com/kubernetes-sigs/gateway-api/config/crd?ref=v1.0.0
customresourcedefinition.apiextensions.k8s.io/gatewayclasses.gateway.networking.k8s.io configured
customresourcedefinition.apiextensions.k8s.io/gateways.gateway.networking.k8s.io configured
customresourcedefinition.apiextensions.k8s.io/httproutes.gateway.networking.k8s.io configured
customresourcedefinition.apiextensions.k8s.io/referencegrants.gateway.networking.k8s.io configured
```

Tamás you're right, that is an alternative; however, why wasn't it working for you @mahdidarabi?

**Comment by davidkornel** [comment]
@mahdidarabi Do you use zsh? If yes, the `?` char broke the command as it had to be escaped. Like this:
`kubectl apply -k "github.com/kubernetes-sigs/gateway-api/config/crd?ref=v1.0.0" `

**Comment by mahdidarabi** [comment]
Yes, you were right and this command was executed correctly
