### ISSUE TITLE
Feature: Example on how to use `stunner` with https://livekit.io/

### ISSUE THREAD

**Issue by calexandre** [l7mp/stunner#22]
Just like the title says, it would be awesome to provide an example/instructions on how to make stunner work with https://livekit.io/

> LiveKit is an open source project that provides scalable, multi-user conferencing over WebRTC. It's designed to give you everything you need to build real-time audio and/or video experiences in your applications.

**Comment by davidkornel** [comment]
It's already on our board. Actually, I did a small research on that but there were other things I had to cover. I just need a bit of time. Huge thanks for your issues and feature proposals. Btw we're already working on the STUNner - [Jitsi](https://github.com/jitsi) setup as well

**Comment by anishmenon** [comment]
@davidkornel hi what's the status is there any document available? Thanks

**Comment by davidkornel** [comment]
> @davidkornel hi what's the status is there any document available? Thanks

Thanks for asking. We made significant progress integrating Livekit with STUNner. At this point, we are able to run STUNner and Livekit together. There are no docs yet because we are still experiencing it, but in a week or two, we plan to release an initial document and a demo. Bear with us

**Comment by davidkornel** [comment]
@calexandre @anishmenon  Just opened a PR with the requested LiveKit integration. Follow it if you are still interested.
