### ISSUE TITLE
Question: How to config TURN Server to Mediasoup Server?

### ISSUE THREAD

**Issue by rg9z** [l7mp/stunner#58]
Hello, I am newbie Kubernetes.
I am creating a server with mediasoup and following the stunner instructions i seem to have successfully created a TURN server.
I have connected the client to TURN Sever but nothing works. I think in next step, I need to connect my TURN Server to my Mediasoup Server, right?.
Any answers help, thanks in advance.

**Comment by damhau** [comment]
Hi Guys,

I've spend quite a bit of time to make Mediasoup work with Stunner so I write a how to here: https://github.com/damhau/mediasoup-demo-docker (I know the repo is called docker but it is also for K8s with Stunner).
I took some of the information form the doc of Stunner and used it in my README.md I hope this is ok.

Let me know if this is usefull.

**Comment by rg0now** [comment]
This is truly amazing, thanks! Do you mind if we adopt a super-simplified version of your writeup as a STUNner tutorial, namely the Kubernetes stuff? Of course, we'd clearly acknowledge you. And thx for the hard work!

**Comment by damhau** [comment]
Nice, I'm happy it is usefull. Of course you can use it no problem.

**Comment by levaitamas** [comment]
Awesome, thanks @damhau!  @davidkornel added a great mediasoup tutorial based on your work: https://github.com/l7mp/stunner/tree/main/docs/examples/mediasoup
