### ISSUE TITLE
Request for providing images for arm architecture (raspberry pi)

### ISSUE THREAD

**Issue by LeaTaka** [l7mp/stunner#75]
Hi there, I compiled the images that are used by your helm charts for arm64.
https://gitlab.com/leataka/yiqi/janus-stunner

Unfortunately it is not enough to make it work.

Stunner works fantastic, now my goal is to run janus webrtc on an rpi4b-8GB which is linux/arm64.
Can you please help?

**Comment by levaitamas** [comment]
Hi @LeaTaka!

That sounds like an interesting project. I am not quite sure if I understood correctly what is missing in your setup. 
- *Integrating Janus with STUNner?* We have a tutorial on deploying [Jitsi with STUNner](https://github.com/l7mp/stunner/tree/main/examples/jitsi). Hope it might be somewhat useful for Janus. 
- *STUNner ARM64 images?* We do not build them since we have no capacity (and apparatus) for testing arm64 images. We can build them for sure, but take no guarantees.  
- Do you encounter some sort of *error messages* or something like that?

**Comment by LeaTaka** [comment]
Hey there, thanks for the swift reply!
1. I did some extensive testing with Janus on x86 and arm platforms both on bare metal and K8s. It works :-) My setup with stunner on x86 works like a charm. Now I need to get it running behind a nat on the rpi4B so I can get rid of the cloud provider.
2. Can I assist? I have the feeling that some code is not compatible as I have tested your images with correct arm64 manifest information.
3. Well yes, but not much: `standard_init_linux.go:228: exec user process caused: exec format error` Most of the time this indicates an architecture mismatch. However is the output from the manifest-tool inspect:
`
$ ./manifest-tool-linux-arm64-2.0.8 --username ${CI_REGISTRY_USER} --password ${CI_REGISTRY_PASSWORD} \ # collapsed multi-line command
Name: registry.gitlab.com/leataka/yiqi/janus-stunner/stunner-gateway-operator:latest (Type: application/vnd.docker.distribution.manifest.v2+json)
      Digest: sha256:f3766cb82d8c4882a09b626ae1be74b0a74faba46f629ed356116b0dfce2004d
        Size: 592
          OS: linux
        Arch: arm64
    # Layers: 2
      layer 01: digest = sha256:fc251a6e798157dc3b46fd265da72f39cd848e3f9f4a0b28587d1713b878deb9
      layer 02: digest = sha256:ef89929f784972c8f5305c8048da0fa6b25e03e7076f3c6829c67983dc4f2582
$ ./manifest-tool-linux-arm64-2.0.8 --username ${CI_REGISTRY_USER} --password ${CI_REGISTRY_PASSWORD} \ # collapsed multi-line command
Name: registry.gitlab.com/leataka/yiqi/janus-stunner/stunnerd:latest (Type: application/vnd.docker.distribution.manifest.v2+json)
      Digest: sha256:7c798ed3e66db024cb0dddca412aa27443285fb15fa8b4394e401316636691d4
        Size: 747
          OS: linux
        Arch: arm64
    # Layers: 3
      layer 01: digest = sha256:7affad345de4d8ac241e78fcbfe6cb38554fda367ded773df715b3624c685620
      layer 02: digest = sha256:a6d6123738b58f0a914bdb9664239730e6441c7374e701c59410542a2a2b0161
      layer 03: digest = sha256:5a2dd0f2bc86f559973857afa6f4d259e97b43575563b4b1d820ca931619aaf4
$ ./manifest-tool-linux-arm64-2.0.8 --username ${CI_REGISTRY_USER} --password ${CI_REGISTRY_PASSWORD} \ # collapsed multi-line command
Name: registry.gitlab.com/leataka/yiqi/janus-stunner/stunner-job:latest (Type: application/vnd.docker.distribution.manifest.v2+json)
      Digest: sha256:fd9ced202cd59be4104137912ed700e722d706037548b0d30b2e692d6f997c83
        Size: 754
          OS: linux
        Arch: arm64
    # Layers: 3
      layer 01: digest = sha256:e96e057aae67380a4ddb16c337c5c3669d97fdff69ec537f02aa2cc30d814281
      layer 02: digest = sha256:c6298e08a61c2cc51043479095326d84be10a7fab22d3a0d4d8339a0cd0dd88b
      layer 03: digest = sha256:aa620ba929d3f47347a6512b7d8adf5205b8a17d250d1dcde7de44710ae9fa72
`

**Comment by LeaTaka** [comment]
Fantastic, will test tomorrow!!

**Comment by LeaTaka** [comment]
Amazing !!
I can confirm stunner/stunner-dev and stunner/stunner-gateway-operator-dev WORKS on raspberry pi arm64 architecture !!
Thanks alot and let me know if I can help you out anytime!

**Comment by levaitamas** [comment]
Awesome! Happy to hear that it works!

I will close this issue for now since the original issue seems resolved. Feel free to (re-)open if you encounter any issues.
