### ISSUE TITLE
Publish workflow fails if separately pushed commits are too rapid

### ISSUE THREAD

**Issue by davidkornel** [l7mp/stunner#86]
**Issue**: If there are two commits pushed separately after each other in a short time span. The second job in the stunner-helm repo will have a different local l7mp.io head, which will block the push.

**Solution**: Prevent two jobs running from the same action at the same time. Queueing them would be a good solution

**Comment by levaitamas** [comment]
No issues in the last N months, and we made some improvements in https://github.com/l7mp/stunner-helm/commit/dee005add64fe9dab3a3a358869b989362277bb8. Closing this for now.
