### ISSUE TITLE
Question: Can stunner be used as a pure relay server 

### ISSUE THREAD

**Issue by piggywave** [l7mp/stunner#88]
**Description:**
I am deploying stunner in k8s as a pure turn server(with gateway operator), which all clients are out of the cluster. And clients has created data channel successfully, but for video stream, for the peer ip does not in the endpoint list(which is stunner's clusterip and pod ip), the permission was denied.  Is it possible to set the endpoint to 0.0.0.0/0?

here is the code where the IP was compared:
[https://github.com/l7mp/stunner/blob/v0.14.0/internal/object/cluster.go#L197](url)

because I am not familiar with turn, is there something wrong I have misunderstood？any info will be helpful, thanks.

**some stunner daemon logs:**
`06:21:08.720580 cluster.go:189: stunner-cluster-sweeper/stunner-headless TRACE: Route: cluster "sweeper/stunner-headless" of type STATIC, peer IP: 0.0.1.1
06:21:08.720588 cluster.go:196: stunner-cluster-sweeper/stunner-headless TRACE: considering endpoint {"10.0.0.143" "ffffffff"}
06:21:08.720593 cluster.go:196: stunner-cluster-sweeper/stunner-headless TRACE: considering endpoint {"10.254.123.34" "ffffffff"}
06:21:08.720597 handlers.go:118: stunner-auth DEBUG: permission denied on listener "sweeper/udp-gateway/udp-listener" for client "172.19.24.29:10709" to peer 0.0.1.1: no route to endpoint
06:21:08.720601 turn.go:235: turn INFO: permission denied for client 172.19.24.29:10709 to peer 0.0.1.1
06:21:08.727499 handlers.go:37: stunner-auth INFO: plaintext auth request: username="admin" realm="stunner.l7mp.io" srcAddr=172.19.24.29:10709
06:21:08.727512 handlers.go:101: stunner-auth DEBUG: permission handler for listener "sweeper/udp-gateway/udp-listener": client "172.19.24.29:10709", peer "0.0.1.1"
06:21:08.727516 handlers.go:106: stunner-auth TRACE: considering route to cluster "sweeper/stunner-headless"
06:21:08.727520 handlers.go:108: stunner-auth TRACE: considering cluster "sweeper/stunner-headless"
06:21:08.727523 cluster.go:189: stunner-cluster-sweeper/stunner-headless TRACE: Route: cluster "sweeper/stunner-headless" of type STATIC, peer IP: 0.0.1.1
06:21:08.727528 cluster.go:196: stunner-cluster-sweeper/stunner-headless TRACE: considering endpoint {"10.0.0.143" "ffffffff"}
06:21:08.727532 cluster.go:196: stunner-cluster-sweeper/stunner-headless TRACE: considering endpoint {"10.254.123.34" "ffffffff"}
06:21:08.727536 handlers.go:118: stunner-auth DEBUG: permission denied on listener "sweeper/udp-gateway/udp-listener" for client "172.19.24.29:10709" to peer 0.0.1.1: no route to endpoint
06:21:08.727543 turn.go:235: turn INFO: permission denied for client 172.19.24.29:10709 to peer 0.0.1.1
06:21:37.009777 handlers.go:37: stunner-auth INFO: plaintext auth request: username="admin" realm="stunner.l7mp.io" srcAddr=172.19.24.29:10709`

**Comment by rg0now** [comment]
Unfortunately this is currently blocking on this [issue](https://github.com/l7mp/stunner-gateway-operator/issues/23). No takers yet, but we will definitely get to implement this sooner than later. We are concentrating on eBPF acceleration right now, please bear with us for a couple of weeks yet, it will be really cool!...:-)

The easy workaround is to use STUNner in the [headless deployment model](https://github.com/l7mp/stunner/blob/main/docs/OBSOLETE.md) and specifying it as the TURN server for *all* clients and servers: in this case everyone will create a TURN allocation on STUNner and STUNner will connect clients to servers (note that in this case the [UDPRoute backend must be STUNner itself](https://github.com/l7mp/stunner/blob/main/docs/examples/direct-one2one-call/README.md#stunner-configuration)). If you really want to use STUNner with the asymmetric ICE mode as a public TURN server then you can fall back to the [standalone mode](https://github.com/l7mp/stunner/blob/main/docs/OBSOLETE.md), but this is not really recommended as of now.

**Comment by piggywave** [comment]
Thanks for you reply, I will try the standalone mode and turn back to operator when this feature implemented.

**Comment by rg0now** [comment]
This feature is now available in the latest dev release, see  https://github.com/l7mp/stunner-gateway-operator/commit/5aed1633bbc71a32a7a38c33bfabffa45824ceb9.
