### ISSUE TITLE
Use of Nodeport instead of LoadBalancer

### ISSUE THREAD

**Issue by cdkey22** [l7mp/stunner#89]
Hello, 
I'm currently trying to install stunner on my k8s cluster but my provider doesn't support UDP LoadBalancer. Is there a way to use a NodePort when creating UDP-Gateway instead of a UDP Loadbalancer ?
Thanks in advance.

**Comment by rg0now** [comment]
Actually, this should automatically work: as long as STUNner cannot find a public LoadBalancer IP for the Service it creates to expose your Gateway it will automatically fall back to the NodePort.

Below is a sample output for a case when this happens: the public IP `34.116.220.190` belongs to one of our Kubernetes nodes in the GKE cluster this output is taken from and the public port is 30501, a typical port in the default NodePort range:

```
$ cmd/stunnerctl/stunnerctl running-config stunner/stunnerd-config
STUN/TURN authentication type:  plaintext
STUN/TURN username:             user-1
STUN/TURN password:             pass-1
Listener 1
        Name:   udp-listener
        Listener:       udp-listener
        Protocol:       UDP
        Public address: 34.116.220.190
        Public port:    30501
```

Note that currently there is no way to enforce the public port for the NodePort service (i.e., 30501), this will be chosen automatically by Kubernetes. There are workarounds, but they are somewhat cumbersome. Note also that you will have to manually open the NodePort range (32000-32767) on the cloud firewall (this is automatically done when you use LoadBalancer services).

**Comment by cdkey22** [comment]
Hello, 
This is interesting but actually i don't see any NodePort Service (for stunner) in the list of generated service (using k get svc --all-namespaces).

Is this normal ?
When I run stunnerctl i see that : 
```
STUN/TURN authentication type:	static
STUN/TURN username:		user-1
STUN/TURN password:		pass-1
Listener 1
	Name:	stunner/udp-gateway/udp-listener
	Listener:	stunner/udp-gateway/udp-listener
	Protocol:	UDP
	Public port:	30200
```
Can you tell me more ?
Tks in advance.

**Comment by rg0now** [comment]
It seems that STUNner has already picked up the NodePort service. The way you know this is by looking at the public port: when the public port is in the [default Nodeport range (32000-32767)](https://www.thinkcode.se/blog/2019/02/20/kubernetes-service-node-port-range) then most probably STUNner has failed to find a LoadBalancer service and fell back to NodePort.

The curious thing here is that there is no public IP: this means that your Kubernetes nodes either run without a public IP (are you using a GKE private cluster?) or the public IP of your nodes is somehow encoded in a nonstandard way in the Kubernetes Node resources.

The easiest way to debug this is to look at the output of `kubectl get nodes -o yaml`  and looking at the `status` field. Is there an external IP? Is it routable?

As per manually creating the service that exposes STUNner: that is a perfectly valid way to expose STUNner precisely the way you want if you don't like the service created automatically by STUNner. That being said, manually creating the NodePort service will not solve your problem until we find out why there are no public IPs assigned by Kubernetes to your nodes. And when we find out, STUNner will automatically find them too and you wouldn't need the manual service any more...:-)

**Comment by cdkey22** [comment]
Ok that's very interesting.

By the way i'm trying to proxy my sip call to a freeswitch server. 
The idea is that I can avoid to open the differents rtc_media_port via a node-port as I'm doing it now (using restriction of port 30000-30100).
It's ok for me, the turn server is correctly recognized etc.
The ip provided as a relay in the sdp seems to be ok provided private ip adress of stunner pod (i think it's normal).
I guess the next thing to do is understanding why freeswitch doesn't wan't to use this private IP to establish connection.

Thank's for all

**Comment by rg0now** [comment]
>  I guess the next thing to do is understanding why freeswitch doesn't wan't to use this private IP to establish connection.

I'm not sure we can be of big help on this matter but we'd be happy to learn more about your use. [Join our Discord](https://discord.gg/DyPgEsbwzc) and tell us about your use of STUNner, maybe someone will show up who understands freeswitch!

Closing this for now, feel free to reopen if anything interesting comes up.

**Comment by smeng9** [comment]
Hi @rg0now you have mentioned 

> There are workarounds, but they are somewhat cumbersome

Do you know such workarounds for me to choose a static Nodeport rather than letting Kubernetes randomly assign one?

**Comment by rg0now** [comment]
> There are workarounds, but they are somewhat cumbersome

The workaround that I had in mind was manually creating the service that exposes STUNner and enforcing the fix NodePort in the manually created Service. Here are some simple steps to do that:
- First make sure STUNner's automatically created Service is internal (we will create the external Service manually, no need for two Services). This can be done by adding the annotation `stunner.l7mp.io/service-type: ClusterIP`, which will instruct STUNner to create a ClusterIP Service instead of the default LoadBalancer.
- Then create a copy of the Service created by STUNner under a new name (new name is important, otherwise STUNner will reset your modifications), set the Service type to NodePort, and set a fixed NodePort value to something you opened on the firewall.
- Create a manual ICE server config for your clients: the public IP would be the external IP of any of your nodes and the public port would be the chosen NodePort. This will be static, but it would at least work. Ephemeral authentication would need additional work though. 

Since you are not the first one requesting for a way to fix the NodePort, I've created an [wishlist item](https://github.com/l7mp/stunner/issues/137) covering this. Once we get some free cycles we'll get to implement this, stay tuned.

**Comment by rg0now** [comment]
> Do you know such workarounds for me to choose a static Nodeport rather than letting Kubernetes randomly assign one?

This is now implemented in https://github.com/l7mp/stunner-gateway-operator/commit/b92ef6a99766c5ac0b3fadcf94aca8e2bb9f55f0, you can install it from the [`dev`](https://github.com/l7mp/stunner/blob/main/docs/INSTALL.md#development-version) channel. Dear @smeng9, can you please test this and report any problem you find?
