### ISSUE TITLE
doc: Code snippets of some examples rendered incorrectly on readthedocs

### ISSUE THREAD

**Issue by levaitamas** [l7mp/stunner#95]
Code snippets of some examples are rendered incorrectly on the readthedocs:
- multiline blocks are rendered as multiple singe-line
- javascript code snippets are not rendered as code blocks
- some `code` blocks rendered correctly, some not
- etc. 
 
Examples affected:
- https://docs.l7mp.io/en/latest/examples/direct-one2one-call/ 
- https://docs.l7mp.io/en/latest/examples/kurento-one2one-call/

**Comment by rg0now** [comment]
rtd does not seem to understand `'''console...'''` notation either

**Comment by levaitamas** [comment]
> * javascript code snippets are not rendered as code blocks

Update: this could happen because of using `js` instead of `javascript` in codeblocks.

> rtd does not seem to understand `'''console...'''` notation either

Strange, it works in the INSTALL:  
- source with `console`: https://raw.githubusercontent.com/l7mp/stunner/main/docs/INSTALL.md
- rtd version looks good: https://docs.l7mp.io/en/latest/INSTALL/

**Comment by levaitamas** [comment]
**Update:**  AUTHENTICATION is broken too: https://docs.l7mp.io/en/latest/AUTH/

Common in these pages is that the wrong codeblocks do not start at the beginning of the line (e.g., there is an indentation because of a numbered list).  @VidarHUN could you double-check that?

**Comment by VidarHUN** [comment]
Fxed: [2459ff2](https://github.com/l7mp/stunner/commit/2459ff21e1b6fd0543e1aa0172d83c28ebf3015b)
