### ISSUE TITLE
Pod Can't connect the stunner server

### ISSUE THREAD

**Issue by FLM210** [l7mp/stunner#98]
I deployed a service in a different namespace than Stunner, Stunner has some error messages when I access the service
![image](https://github.com/l7mp/stunner/assets/38482970/76250c95-a778-4aeb-b455-61493b62dc56)
10.42.0.180 is my service pod IP  10.42.0.181 is stunner pod ip

**Comment by levaitamas** [comment]
Hi @FLM210,

Could you please check whether your situation is similar to #90 or not?

**Comment by FLM210** [comment]
> Hi @FLM210,
> 
> Could you please check whether your situation is similar to #90 or not?

Yeah ,my situation is the same as that
